name: Sync dist/ to target repo and create PR

on:
  push:
    branches:
      - main

env:
  TARGET_REPO: ${{ secrets.TARGET_REPO }}
  TARGET_DIR: ${{ secrets.TARGET_DIR }}
  TARGET_BRANCH: ${{ secrets.TARGET_BRANCH }}

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone target repository
        run: |
          git clone --single-branch --branch $TARGET_BRANCH https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ env.TARGET_REPO }}.git target-repo

      - name: Sync dist/ to target subdirectory
        run: |
          mkdir -p target-repo/${{ env.TARGET_DIR }}
          rm -rf target-repo/${{ env.TARGET_DIR }}/*
          cp -r dist/* target-repo/${{ env.TARGET_DIR }}/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          path: ./target-repo
          commit-message: "sync: update ${{ env.TARGET_DIR }} from dist/"
          branch: sync-${{ env.TARGET_DIR }}-${{ github.run_id }}
          base: ${{ env.TARGET_BRANCH }}
          title: "sync: ${{ github.event.head_commit.message }}"
          body: |
            This PR updates \`${{ env.TARGET_DIR }}/\` with the contents of \`dist/\`.

            ### Trigger Info
            - **Source commit:** [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            - **Message:** ${{ github.event.head_commit.message }}
            - **Pushed by:** ${{ github.actor }}

            ---
            Generated by GitHub Actions on `${{ github.repository }}`
